%Lab1-Circuit analysis methods                        Academic Year 2020/2021
%                                                            TCFE
%Authors:
%Joana Matos, 95799
%Ricardo Abreu, 95842
%Vasco Emídio, 95856
%MEAer
close all
clear all

%%SYMBOLIC COMPUTATIONS

pkg load symbolic

syms R1
syms R2
syms R3
syms R4
syms R5
syms R6
syms R7
syms Va
syms Vb
syms Vc
syms Ib
syms Ic
syms Id
syms Kb
syms Kc
syms Ias
syms Ibs


%%NUMERIC COMPUTATIONS
 %---Data generated by Python 2.7---
 printf("Data:  V, A, Ohm, S")
 R1 = 1.00147062639e3
 R2 = 2.0078068512e3
 R3 = 3.11269704405e3
 R4 = 4.10609573471e3 
 R5 = 3.02670672634e3
 R6 = 2.01292455078e3
 R7 = 1.02905244808e3
 Va = 5.24842063411 
 Id = 1.04086013403e-3 
 Kb = 7.21413591579e-3 
 Kc = 8.01455113996e-3 

 %---Mesh Analysis---
 Am=[R1+R3+R4,R3     ,R4         ,0;
     Kb*R3   ,Kb*R3-1,0          ,0;
     R4      ,0      ,R4+R6+R7-Kc,0;
     0       ,0      ,0          ,1];                   %matrix form
 Bm=[Va; 0; 0; Id];
 
 Im=Am\Bm;                                              %mesh currents array
 
printf("Mesh_MTAB \n")
printf("$I_{a}$ = %g \n", Im(1));
printf("$I_{b}$ = %g \n", Im(2));
printf("$I_{c}$ = %g \n", Im(3));
printf("$I_{d}$ = %g \n", Im(4));
printf("Mesh_MEND \n")


 G1=1/R1; G2=1/R2; G3=1/R3; G4=1/R4; G5=1/R5; G6=1/R6; G7=1/R7; %calculate 
                                                                 %conductancies
  
  %---Node Analysis---
 An=[G1,-G1      ,0  ,0 ,0 ,-G6   ,G4+G6;
     G1,-G1-G2-G3,G2 ,0 ,0 ,0     ,0    ;
     0,G2+Kb     ,-G2,0 ,0 ,0     ,0    ;
     0,Kb        ,0  ,G5,0 ,0     ,0    ;
     0,0         ,0  ,0 ,G7,-G6-G7,G6   ;
     1,0         ,0  ,0 ,0 ,0     ,-1   ;
     0,0         ,0  ,0 ,1 ,-G6*Kc,G6*Kc ];          %matrix form
 Bn=[0;0;0;Id;0;Va;0];

 Vn=An\Bn;                                           %nodal values vector

 Ic_n=(Vn(7)-Vn(6))*G6
 Vc_n=Kc*Ic_n
 Vb_n=Vn(2)
 Ib_n=Kb*Vb_n
 
printf("Nodal_NTAB \n")
printf("$V_{1}$ = %g \n", Vn(1));
printf("$V_{2}$ = %g \n", Vn(2));
printf("$V_{3}$ = %g \n", Vn(3));
printf("$V_{4}$ = %g \n", Vn(4));
printf("$V_{5}$ = %g \n", Vn(5));
printf("$V_{6}$ = %g \n", Vn(6));
printf("$V_{7}$ = %g \n", Vn(7));
printf("Nodal_NEND \n")